In [1]:
import pandas as pd

In [2]:
orders = pd.read_csv("../data/raw/archive/olist_orders_dataset.csv")

In [3]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
orders.shape

(99441, 8)

In [5]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [6]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

In [7]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [8]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [9]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [10]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 13.0 MB

In [11]:
customers = pd.read_csv("../data/raw/archive/olist_customers_dataset.csv")

In [12]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [13]:
customers.shape

(99441, 5)

In [14]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [15]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB

In [16]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [17]:
customers["customer_id"].nunique()

99441

In [18]:
customers["customer_unique_id"].nunique()

96096

In [19]:
orders_customers = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

In [20]:
orders_customers.shape

(99441, 12)

In [21]:
orders_customers.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [22]:
orders_customers["customer_unique_id"].isnull().sum()

np.int64(0)

In [23]:
orders_customers["order_id"].nunique()

99441

In [24]:
orders_per_customer = (
    orders_customers
    .groupby("customer_unique_id")["order_id"]
    .nunique()
    .sort_values(ascending=False)
)

In [25]:
orders_per_customer.head(10)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
1b6c7548a2a1f9037c1fd3ddfed95f33     7
12f5d6e1cbf93dafd9dcc19095df0b3d     6
de34b16117594161a6a89c50b289d35a     6
63cfc61cee11cbe306bff5857d00bfe4     6
f0e310a6839dce9de1638e0fe5ab282a     6
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
Name: order_id, dtype: int64

In [26]:
repeat_customers = (orders_per_customer > 1).sum()
repeat_customers

np.int64(2997)

In [27]:
repeat_customer_rate = repeat_customers / orders_per_customer.shape[0]

repeat_customer_rate

np.float64(0.031187562437562436)

In [28]:
repeat_customer_rate * 100

np.float64(3.1187562437562435)

In [29]:
order_items = pd.read_csv(
    "../data/raw/archive/olist_order_items_dataset.csv"
)

In [30]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [31]:
order_items.shape

(112650, 7)

In [32]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [33]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 18.4 MB

In [34]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [35]:
order_items["order_id"].nunique()

98666

In [36]:
order_items.shape[0]

112650

In [37]:
items_per_order = (
    order_items
    .groupby("order_id")["order_item_id"]
    .count()
    .sort_values(ascending=False)
)

In [38]:
items_per_order.head(10)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
9bdc4d4c71aa1de4606060929dee888c    14
73c8ab38f07dc94389065f7eba4f297a    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
2c2a19b5703863c908512d135aa6accc    12
c05d6a79e55da72ca780ce90364abed9    12
Name: order_item_id, dtype: int64

In [39]:
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"]
)

In [40]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 16.3 MB

In [41]:
order_items[["price", "freight_value"]].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [42]:
order_items["item_total"] = (
    order_items["price"] + order_items["freight_value"]
)

In [44]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_total
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04

In [45]:
orders_without_items = orders[
    ~orders["order_id"].isin(order_items["order_id"])
]

orders_without_items.shape

(775, 8)

In [46]:
orders_without_items["order_status"].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [47]:
order_details = orders_customers.merge(
    order_items,
    on="order_id",
    how="left"
)

In [48]:
order_details.shape

(113425, 19)

In [49]:
order_details["order_id"].nunique()

99441

In [50]:
order_details["product_id"].isnull().sum()

np.int64(775)

In [51]:
order_details.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_total
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,28.62

In [52]:
order_financials = (
    order_items
    .groupby("order_id")
    .agg(
        product_value=("price", "sum"),
        freight_value=("freight_value", "sum"),
        item_count=("order_item_id", "count")
    )
    .reset_index()
)

In [53]:
order_financials["order_total"] = (
    order_financials["product_value"]
    + order_financials["freight_value"]
)

In [54]:
order_financials.head()

,order_id,product_value,freight_value,item_count,order_total
0,00010242fe8c5a6d1ba2dd792cb16214,58.90,13.29,1,72.19
1,00018f77f2f0320c557190d7a144bdd3,239.90,19.93,1,259.83
2,000229ec398224ef6ca0657da4fc703e,199.00,17.87,1,216.87
3,00024acbcdf0a6daa1e931b038114c75,12.99,12.79,1,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,18.14,1,218.04

In [55]:
order_financials.shape

(98666, 5)

In [56]:
products = pd.read_csv(
    "../data/raw/archive/olist_products_dataset.csv"
)

In [57]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [58]:
products.shape

(32951, 9)

In [59]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [60]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 3.7 MB

In [61]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [62]:
category_translation = pd.read_csv(
    "../data/raw/archive/product_category_name_translation.csv"
)

In [63]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [64]:
category_translation.shape

(71, 2)

In [65]:
category_translation.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 3.5 KB

In [66]:
products_en = products.merge(
    category_translation,
    on="product_category_name",
    how="left"
)

In [67]:
products_en.shape

(32951, 10)

In [68]:
products_en.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

In [69]:
products_en["product_category_name_english"].isnull().sum()

np.int64(623)

In [70]:
untranslated_products = products_en[
    products_en["product_category_name"].notna()
    & products_en["product_category_name_english"].isna()
]

untranslated_products.shape

(13, 10)

In [71]:
untranslated_products[
    ["product_category_name"]
].value_counts()

product_category_name
portateis_cozinha_e_preparadores_de_alimentos    10
pc_gamer                                          3
Name: count, dtype: int64

In [72]:
untranslated_products["product_category_name"].nunique()

2

In [73]:
products["product_id"].nunique()

32951

In [74]:
products.shape[0]

32951

In [75]:
order_details_products = order_details.merge(
    products_en,
    on="product_id",
    how="left",
    validate="many_to_one"
)

In [76]:
order_details_products.shape

(113425, 28)

In [77]:
order_details_products["order_id"].nunique()

99441

In [78]:
order_details_products["product_id"].isnull().sum()

np.int64(775)

In [79]:
delivered_sales = order_details_products[
    (order_details_products["order_status"] == "delivered")
    & (order_details_products["product_id"].notna())
].copy()

In [80]:
delivered_sales["category"] = (
    delivered_sales["product_category_name_english"]
    .fillna(delivered_sales["product_category_name"])
    .fillna("unknown")
)

In [81]:
top_categories_by_items = (
    delivered_sales
    .groupby("category")
    .size()
    .sort_values(ascending=False)
)

top_categories_by_items.head(10)

category
bed_bath_table           10953
health_beauty             9465
sports_leisure            8431
furniture_decor           8160
computers_accessories     7644
housewares                6795
watches_gifts             5859
telephony                 4430
garden_tools              4268
auto                      4140
dtype: int64

In [82]:
top_categories_by_sales = (
    delivered_sales
    .groupby("category")["price"]
    .sum()
    .sort_values(ascending=False)
)

top_categories_by_sales.head(10)

category
health_beauty            1233131.72
watches_gifts            1166176.98
bed_bath_table           1023434.76
sports_leisure            954852.55
computers_accessories     888724.61
furniture_decor           711927.69
housewares                615628.69
cool_stuff                610204.10
auto                      578966.65
toys                      471286.48
Name: price, dtype: float64

In [83]:
avg_price_by_category = (
    delivered_sales
    .groupby("category")["price"]
    .mean()
    .sort_values(ascending=False)
)

avg_price_by_category.head(10)

category
computers                                        1098.915276
small_appliances_home_oven_and_coffee             638.213151
home_appliances_2                                 467.333117
agro_industry_and_commerce                        342.553883
musical_instruments                               283.127097
portateis_cozinha_e_preparadores_de_alimentos     280.973571
small_appliances                                  277.741824
fixed_telephony                                   216.922392
construction_tools_safety                         211.875519
watches_gifts                                     199.040276
Name: price, dtype: float64

In [84]:
orders_by_category = (
    delivered_sales
    .groupby("category")["order_id"]
    .nunique()
    .sort_values(ascending=False)
)

orders_by_category.head(10)

category
bed_bath_table           9272
health_beauty            8647
sports_leisure           7530
computers_accessories    6530
furniture_decor          6307
housewares               5743
watches_gifts            5495
telephony                4093
auto                     3810
toys                     3804
Name: order_id, dtype: int64

In [85]:
category_summary = (
    delivered_sales
    .groupby("category")
    .agg(
        item_count=("order_item_id", "count"),
        order_count=("order_id", "nunique"),
        sales_value=("price", "sum"),
        avg_item_price=("price", "mean"),
        freight_value=("freight_value", "sum")
    )
    .sort_values("sales_value", ascending=False)
)

category_summary.head(10)

,item_count,order_count,sales_value,avg_item_price,freight_value
category,,,,,
health_beauty,9465,8647,1233131.72,130.283330,178957.81
watches_gifts,5859,5495,1166176.98,199.040276,98156.14
bed_bath_table,10953,9272,1023434.76,93.438762,201774.50
sports_leisure,8431,7530,954852.55,113.254958,163404.36
computers_accessories,7644,6530,888724.61,116.264339,143999.16
furniture_decor,8160,6307,711927.69,87.246040,168402.23
housewares,6795,5743,615628.69,90.600249,142763.56
cool_stuff,3718,3559,610204.10,164.121598,81476.79
auto,4140,3810,578966.65,139.847017,90488.10
toys,4030,3804,471286.48,116.944536,75774.58

In [86]:
category_summary["freight_ratio"] = (
    category_summary["freight_value"]
    / (category_summary["sales_value"] + category_summary["freight_value"])
)

In [87]:
category_summary.head(10)

,item_count,order_count,sales_value,avg_item_price,freight_value,freight_ratio
category,,,,,,
health_beauty,9465,8647,1233131.72,130.283330,178957.81,0.126733
watches_gifts,5859,5495,1166176.98,199.040276,98156.14,0.077635
bed_bath_table,10953,9272,1023434.76,93.438762,201774.50,0.164686
sports_leisure,8431,7530,954852.55,113.254958,163404.36,0.146124
computers_accessories,7644,6530,888724.61,116.264339,143999.16,0.139436
furniture_decor,8160,6307,711927.69,87.246040,168402.23,0.191294
housewares,6795,5743,615628.69,90.600249,142763.56,0.188245
cool_stuff,3718,3559,610204.10,164.121598,81476.79,0.117795
auto,4140,3810,578966.65,139.847017,90488.10,0.135167
toys,4030,3804,471286.48,116.944536,75774.58,0.138512

In [88]:
top_categories_by_items.head(10)

category
bed_bath_table           10953
health_beauty             9465
sports_leisure            8431
furniture_decor           8160
computers_accessories     7644
housewares                6795
watches_gifts             5859
telephony                 4430
garden_tools              4268
auto                      4140
dtype: int64

In [89]:
delivered_order_financials = orders_customers[
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "customer_unique_id"
    ]
].merge(
    order_financials,
    on="order_id",
    how="inner",
    validate="one_to_one"
)

delivered_order_financials = delivered_order_financials[
    delivered_order_financials["order_status"] == "delivered"
].copy()

In [90]:
delivered_order_financials.shape

(96478, 8)

In [91]:
gmv = delivered_order_financials["product_value"].sum()

order_count = delivered_order_financials["order_id"].nunique()

customer_count = delivered_order_financials[
    "customer_unique_id"
].nunique()

aov = gmv / order_count

avg_items_per_order = delivered_order_financials[
    "item_count"
].mean()

total_freight = delivered_order_financials[
    "freight_value"
].sum()

freight_ratio = total_freight / (
    gmv + total_freight
)

In [92]:
print(f"GMV: {gmv:,.2f}")
print(f"Orders: {order_count:,}")
print(f"Customers: {customer_count:,}")
print(f"AOV: {aov:.2f}")
print(f"Average items per order: {avg_items_per_order:.2f}")
print(f"Freight ratio: {freight_ratio:.2%}")

GMV: 13,221,498.11
Orders: 96,478
Customers: 93,358
AOV: 137.04
Average items per order: 1.14
Freight ratio: 14.26%

In [93]:
delivered_order_financials["month"] = (
    delivered_order_financials["order_purchase_timestamp"]
    .dt.to_period("M")
)

In [94]:
monthly_kpis = (
    delivered_order_financials
    .groupby("month")
    .agg(
        gmv=("product_value", "sum"),
        orders=("order_id", "nunique"),
        customers=("customer_unique_id", "nunique"),
        items=("item_count", "sum"),
        freight=("freight_value", "sum")
    )
)

In [95]:
monthly_kpis["aov"] = (
    monthly_kpis["gmv"] / monthly_kpis["orders"]
)

monthly_kpis["avg_items_per_order"] = (
    monthly_kpis["items"] / monthly_kpis["orders"]
)

monthly_kpis["freight_ratio"] = (
    monthly_kpis["freight"]
    / (monthly_kpis["gmv"] + monthly_kpis["freight"])
)

In [96]:
monthly_kpis.tail(12)

,gmv,orders,customers,items,freight,aov,avg_items_per_order,freight_ratio
month,,,,,,,,
2017-09,607399.67,4150,4083,4737,93677.82,146.361366,1.141446,0.133620
2017-10,648247.65,4478,4417,5214,102869.36,144.762762,1.164359,0.136955
2017-11,987765.37,7289,7183,8475,165598.83,135.514525,1.162711,0.143579
2017-12,726033.19,5513,5450,6187,117045.10,131.694756,1.122256,0.138831
2018-01,924645.00,7069,6974,8037,153242.46,130.802801,1.136936,0.142169
2018-02,826437.13,6555,6400,7518,139731.28,126.077365,1.146911,0.144624
2018-03,953356.25,7003,6914,8017,167241.99,136.135406,1.144795,0.149243
2018-04,973534.09,6798,6744,7827,159344.84,143.208898,1.151368,0.140655
2018-05,977544.69,6749,6693,7810,151229.83,144.842894,1.157208,0.133977
2018-06,856077.86,6099,6061,7010,155900.43,140.363643,1.149369,0.154055
2018-07,867953.46,6159,6100,6963,159853.82,140.924413,1.130541,0.155529
2018-08,838576.64,6351,6310,7142,146915.00,132.038520,1.124547,0.149078

In [97]:
jul = monthly_kpis.loc[pd.Period("2018-07", freq="M")]
aug = monthly_kpis.loc[pd.Period("2018-08", freq="M")]

In [98]:
jul_avg_item_price = jul["gmv"] / jul["items"]
aug_avg_item_price = aug["gmv"] / aug["items"]

In [99]:
comparison = pd.DataFrame({
    "July": [
        jul["gmv"],
        jul["orders"],
        jul["customers"],
        jul["aov"],
        jul["avg_items_per_order"],
        jul_avg_item_price
    ],
    "August": [
        aug["gmv"],
        aug["orders"],
        aug["customers"],
        aug["aov"],
        aug["avg_items_per_order"],
        aug_avg_item_price
    ]
}, index=[
    "GMV",
    "Orders",
    "Customers",
    "AOV",
    "Avg Items per Order",
    "Avg Item Price"
])

comparison

                              July         August
GMV                  867953.460000  838576.640000
Orders                 6159.000000    6351.000000
Customers              6100.000000    6310.000000
AOV                     140.924413     132.038520
Avg Items per Order       1.130541       1.124547
Avg Item Price          124.652227     117.414819

In [100]:
comparison["Change %"] = (
    (comparison["August"] / comparison["July"]) - 1
) * 100

comparison.round(2)

                          July     August  Change %
GMV                  867953.46  838576.64     -3.38
Orders                 6159.00    6351.00      3.12
Customers              6100.00    6310.00      3.44
AOV                     140.92     132.04     -6.31
Avg Items per Order       1.13       1.12     -0.53
Avg Item Price          124.65     117.41     -5.81

In [101]:
jul_aov_check = jul_avg_item_price * jul["avg_items_per_order"]
aug_aov_check = aug_avg_item_price * aug["avg_items_per_order"]

print("July AOV check:", jul_aov_check)
print("Actual July AOV:", jul["aov"])

print("August AOV check:", aug_aov_check)
print("Actual August AOV:", aug["aov"])

July AOV check: 140.92441305406723
Actual July AOV: 140.9244130540672
August AOV check: 132.03851991812314
Actual August AOV: 132.03851991812314

In [102]:
delivered_sales["month"] = (
    delivered_sales["order_purchase_timestamp"]
    .dt.to_period("M")
)

In [103]:
jul_aug_sales = delivered_sales[
    delivered_sales["month"].isin([
        pd.Period("2018-07", freq="M"),
        pd.Period("2018-08", freq="M")
    ])
].copy()

In [104]:
category_monthly_gmv = (
    jul_aug_sales
    .groupby(["category", "month"])["price"]
    .sum()
    .unstack(fill_value=0)
)

In [105]:
category_monthly_gmv.columns

PeriodIndex(['2018-07', '2018-08'], dtype='period[M]', name='month')

In [106]:
category_monthly_gmv = category_monthly_gmv.rename(
    columns={
        pd.Period("2018-07", freq="M"): "July_GMV",
        pd.Period("2018-08", freq="M"): "August_GMV"
    }
)

In [107]:
category_monthly_gmv["GMV_change"] = (
    category_monthly_gmv["August_GMV"]
    - category_monthly_gmv["July_GMV"]
)

In [108]:
category_monthly_gmv["Change_%"] = (
    category_monthly_gmv["GMV_change"]
    / category_monthly_gmv["July_GMV"]
    * 100
)

In [109]:
category_decline = category_monthly_gmv.sort_values(
    "GMV_change"
)

category_decline.head(10).round(2)

month                    July_GMV  August_GMV  GMV_change  Change_%
category
watches_gifts            95164.79    69767.06   -25397.73    -26.69
garden_tools             25639.88    16314.70    -9325.18    -36.37
fixed_telephony           9319.39     2724.17    -6595.22    -70.77
office_furniture         13225.28     6758.87    -6466.41    -48.89
cool_stuff               21152.01    15794.89    -5357.12    -25.33
home_appliances_2        12597.32     7532.76    -5064.56    -40.20
costruction_tools_tools   5501.20     1255.77    -4245.43    -77.17
furniture_decor          45393.59    41168.55    -4225.04     -9.31
consoles_games            8519.11     4381.31    -4137.80    -48.57
housewares               62583.30    58763.36    -3819.94     -6.10

In [110]:
category_growth = category_monthly_gmv.sort_values(
    "GMV_change",
    ascending=False
)

category_growth.head(10).round(2)

month                             July_GMV  August_GMV  GMV_change  Change_%
category
health_beauty                    103524.22   119391.01    15866.79     15.33
telephony                         26492.68    36572.91    10080.23     38.05
construction_tools_construction   15237.47    22917.16     7679.69     50.40
bed_bath_table                    54405.23    60891.09     6485.86     11.92
pet_shop                          19343.85    24608.07     5264.22     27.21
food                               3378.17     8174.18     4796.01    141.97
perfumery                         20645.97    24839.74     4193.77     20.31
musical_instruments                7871.93    10519.34     2647.41     33.63
construction_tools_safety          1888.95     3970.22     2081.27    110.18
fashion_bags_accessories           6071.07     8127.53     2056.46     33.87

In [111]:
def compare_category(category_name):
    category_data = (
        jul_aug_sales[
            jul_aug_sales["category"] == category_name
        ]
        .groupby("month")
        .agg(
            gmv=("price", "sum"),
            orders=("order_id", "nunique"),
            customers=("customer_unique_id", "nunique"),
            items=("order_item_id", "count"),
            avg_item_price=("price", "mean")
        )
    )

    category_data["aov"] = (
        category_data["gmv"] / category_data["orders"]
    )

    category_data["avg_items_per_order"] = (
        category_data["items"] / category_data["orders"]
    )

    july = category_data.loc[
        pd.Period("2018-07", freq="M")
    ]

    august = category_data.loc[
        pd.Period("2018-08", freq="M")
    ]

    comparison = pd.DataFrame({
        "July": july,
        "August": august,
        "Change %": ((august / july) - 1) * 100
    })

    return comparison.round(2)

In [112]:
watches_analysis = compare_category("watches_gifts")
watches_analysis

                         July    August  Change %
gmv                  95164.79  69767.06    -26.69
orders                 507.00    387.00    -23.67
customers              502.00    384.00    -23.51
items                  521.00    411.00    -21.11
avg_item_price         182.66    169.75     -7.07
aov                    187.70    180.28     -3.96
avg_items_per_order      1.03      1.06      3.35

In [113]:
compare_category("garden_tools")

                         July    August  Change %
gmv                  25639.88  16314.70    -36.37
orders                 152.00    120.00    -21.05
customers              152.00    120.00    -21.05
items                  177.00    136.00    -23.16
avg_item_price         144.86    119.96    -17.19
aov                    168.68    135.96    -19.40
avg_items_per_order      1.16      1.13     -2.67

In [114]:
compare_category("fixed_telephony")

                        July   August  Change %
gmv                  9319.39  2724.17    -70.77
orders                  8.00    10.00     25.00
customers               8.00    10.00     25.00
items                  11.00    10.00     -9.09
avg_item_price        847.22   272.42    -67.85
aov                  1164.92   272.42    -76.62
avg_items_per_order     1.38     1.00    -27.27

In [115]:
compare_category("health_beauty")

                          July     August  Change %
gmv                  103524.22  119391.01     15.33
orders                  699.00     765.00      9.44
customers               694.00     765.00     10.23
items                   770.00     835.00      8.44
avg_item_price          134.45     142.98      6.35
aov                     148.10     156.07      5.38
avg_items_per_order       1.10       1.09     -0.91

In [116]:
import sqlite3

In [117]:
db_path = "../data/processed/business.db"

In [118]:
import sqlite3

db_path = "../data/processed/business.db"

conn = sqlite3.connect(db_path)

print("Database connected successfully.")

Database connected successfully.

In [119]:
customers.to_sql(
    "customers",
    conn,
    if_exists="replace",
    index=False
)

orders.to_sql(
    "orders",
    conn,
    if_exists="replace",
    index=False
)

order_items.to_sql(
    "order_items",
    conn,
    if_exists="replace",
    index=False
)

products_en.to_sql(
    "products",
    conn,
    if_exists="replace",
    index=False
)

order_financials.to_sql(
    "order_financials",
    conn,
    if_exists="replace",
    index=False
)

98666

In [120]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name;
"""

pd.read_sql_query(query, conn)

               name
0         customers
1  order_financials
2       order_items
3            orders
4          products

In [121]:
query = """
SELECT *
FROM orders
LIMIT 5;
"""

pd.read_sql_query(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [122]:
query = """
SELECT
    order_status,
    COUNT(*) AS order_count
FROM orders
GROUP BY order_status
ORDER BY order_count DESC;
"""

pd.read_sql_query(query, conn)

  order_status  order_count
0    delivered        96478
1      shipped         1107
2     canceled          625
3  unavailable          609
4     invoiced          314
5   processing          301
6      created            5
7     approved            2

In [123]:
query = """
SELECT
    o.order_id,
    o.order_status,
    o.order_purchase_timestamp,
    c.customer_unique_id,
    c.customer_city,
    c.customer_state
FROM orders AS o
LEFT JOIN customers AS c
    ON o.customer_id = c.customer_id
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,order_id,order_status,order_purchase_timestamp,customer_unique_id,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-02 10:56:33,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,2018-07-24 20:41:37,af07308b275d755c9edb36a90c618231,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,2018-08-08 08:38:49,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,2017-11-18 19:28:06,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,2018-02-13 21:18:39,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP
5,a4591c265e18cb1dcee52889e2d8acc3,delivered,2017-07-09 21:57:05,80bb27c7c16e8f973207a5086ab329e2,congonhinhas,PR
6,136cce7faa42fdb2cefd53fdc79a6098,invoiced,2017-04-11 12:22:08,36edbb3fb164b1f16485364b6fb04c73,santa rosa,RS
7,6514b8ad8028c9f2cc2374ded245783f,delivered,2017-05-16 13:10:30,932afa1e708222e5821dac9cd5db4cae,nilopolis,RJ
8,76c6e866289321a7c93b82b54852dc33,delivered,2017-01-23 18:29:09,39382392765b6dc74812866ee5ee92a7,faxinalzinho,RS
9,e69bfb5eb88e0ed6a785585b27e16dbf,delivered,2017-07-29 11:55:02,299905e3934e9e181bfb2e164dd4b4f8,sorocaba,SP

In [124]:
query = """
SELECT
    SUBSTR(o.order_purchase_timestamp, 1, 7) AS month,
    ROUND(SUM(f.product_value), 2) AS gmv,
    COUNT(DISTINCT o.order_id) AS orders,
    COUNT(DISTINCT c.customer_unique_id) AS customers,
    SUM(f.item_count) AS items,
    ROUND(SUM(f.freight_value), 2) AS freight
FROM orders AS o
JOIN customers AS c
    ON o.customer_id = c.customer_id
JOIN order_financials AS f
    ON o.order_id = f.order_id
WHERE o.order_status = 'delivered'
  AND SUBSTR(o.order_purchase_timestamp, 1, 7)
      IN ('2018-07', '2018-08')
GROUP BY month
ORDER BY month;
"""

sql_monthly = pd.read_sql_query(query, conn)

sql_monthly

     month        gmv  orders  customers  items    freight
0  2018-07  867953.46    6159       6100   6963  159853.82
1  2018-08  838576.64    6351       6310   7142  146915.00

In [125]:
sql_monthly["aov"] = (
    sql_monthly["gmv"] / sql_monthly["orders"]
)

sql_monthly["avg_items_per_order"] = (
    sql_monthly["items"] / sql_monthly["orders"]
)

sql_monthly["freight_ratio"] = (
    sql_monthly["freight"]
    / (sql_monthly["gmv"] + sql_monthly["freight"])
)

sql_monthly.round(2)

,month,gmv,orders,customers,items,freight,aov,avg_items_per_order,freight_ratio
0,2018-07,867953.46,6159,6100,6963,159853.82,140.92,1.13,0.16
1,2018-08,838576.64,6351,6310,7142,146915.00,132.04,1.12,0.15

In [126]:
query = """
SELECT
    COALESCE(
        p.product_category_name_english,
        p.product_category_name,
        'unknown'
    ) AS category,

    ROUND(SUM(
        CASE
            WHEN SUBSTR(o.order_purchase_timestamp, 1, 7) = '2018-07'
            THEN oi.price
            ELSE 0
        END
    ), 2) AS July_GMV,

    ROUND(SUM(
        CASE
            WHEN SUBSTR(o.order_purchase_timestamp, 1, 7) = '2018-08'
            THEN oi.price
            ELSE 0
        END
    ), 2) AS August_GMV

FROM orders AS o

JOIN order_items AS oi
    ON o.order_id = oi.order_id

JOIN products AS p
    ON oi.product_id = p.product_id

WHERE o.order_status = 'delivered'
  AND SUBSTR(o.order_purchase_timestamp, 1, 7)
      IN ('2018-07', '2018-08')

GROUP BY category;
"""

sql_category_gmv = pd.read_sql_query(query, conn)

sql_category_gmv.head()

                     category  July_GMV  August_GMV
0  agro_industry_and_commerce   6669.82     5021.09
1            air_conditioning   2657.86     3556.90
2                         art   1843.20     1481.39
3       arts_and_craftmanship    654.57      901.76
4                       audio   2062.64     2069.40

In [127]:
sql_category_gmv["GMV_change"] = (
    sql_category_gmv["August_GMV"]
    - sql_category_gmv["July_GMV"]
)

sql_category_gmv["Change_%"] = (
    sql_category_gmv["GMV_change"]
    / sql_category_gmv["July_GMV"]
    * 100
)

In [128]:
sql_category_decline = (
    sql_category_gmv
    .sort_values("GMV_change")
)

sql_category_decline.head(10).round(2)

                   category  July_GMV  August_GMV  GMV_change  Change_%
68            watches_gifts  95164.79    69767.06   -25397.73    -26.69
40             garden_tools  25639.88    16314.70    -9325.18    -36.37
32          fixed_telephony   9319.39     2724.17    -6595.22    -70.77
54         office_furniture  13225.28     6758.87    -6466.41    -48.89
19               cool_stuff  21152.01    15794.89    -5357.12    -25.33
43        home_appliances_2  12597.32     7532.76    -5064.56    -40.20
21  costruction_tools_tools   5501.20     1255.77    -4245.43    -77.17
37          furniture_decor  45393.59    41168.55    -4225.04     -9.31
15           consoles_games   8519.11     4381.31    -4137.80    -48.57
47               housewares  62583.30    58763.36    -3819.94     -6.10

In [129]:
sql_category_growth = (
    sql_category_gmv
    .sort_values(
        "GMV_change",
        ascending=False
    )
)

sql_category_growth.head(10).round(2)

,category,July_GMV,August_GMV,GMV_change,Change_%
41,health_beauty,103524.22,119391.01,15866.79,15.33
65,telephony,26492.68,36572.91,10080.23,38.05
16,construction_tools_construction,15237.47,22917.16,7679.69,50.40
7,bed_bath_table,54405.23,60891.09,6485.86,11.92
58,pet_shop,19343.85,24608.07,5264.22,27.21
34,food,3378.17,8174.18,4796.01,141.97
57,perfumery,20645.97,24839.74,4193.77,20.31
53,musical_instruments,7871.93,10519.34,2647.41,33.63
18,construction_tools_safety,1888.95,3970.22,2081.27,110.18
27,fashion_bags_accessories,6071.07,8127.53,2056.46,33.87

In [130]:
def get_monthly_kpis(start_month, end_month, conn):
    query = """
    SELECT
        SUBSTR(o.order_purchase_timestamp, 1, 7) AS month,
        ROUND(SUM(f.product_value), 2) AS gmv,
        COUNT(DISTINCT o.order_id) AS orders,
        COUNT(DISTINCT c.customer_unique_id) AS customers,
        SUM(f.item_count) AS items,
        ROUND(SUM(f.freight_value), 2) AS freight
    FROM orders AS o

    JOIN customers AS c
        ON o.customer_id = c.customer_id

    JOIN order_financials AS f
        ON o.order_id = f.order_id

    WHERE o.order_status = 'delivered'
      AND SUBSTR(o.order_purchase_timestamp, 1, 7)
          BETWEEN ? AND ?

    GROUP BY month
    ORDER BY month;
    """

    result = pd.read_sql_query(
        query,
        conn,
        params=[start_month, end_month]
    )

    result["aov"] = (
        result["gmv"] / result["orders"]
    )

    result["avg_items_per_order"] = (
        result["items"] / result["orders"]
    )

    result["avg_item_price"] = (
        result["gmv"] / result["items"]
    )

    result["freight_ratio"] = (
        result["freight"]
        / (result["gmv"] + result["freight"])
    )

    return result

In [131]:
get_monthly_kpis(
    "2018-07",
    "2018-08",
    conn
).round(2)

,month,gmv,orders,customers,items,freight,aov,avg_items_per_order,avg_item_price,freight_ratio
0,2018-07,867953.46,6159,6100,6963,159853.82,140.92,1.13,124.65,0.16
1,2018-08,838576.64,6351,6310,7142,146915.00,132.04,1.12,117.41,0.15

In [132]:
def get_category_contribution(
    base_month,
    compare_month,
    conn
):
    query = """
    SELECT
        COALESCE(
            p.product_category_name_english,
            p.product_category_name,
            'unknown'
        ) AS category,

        ROUND(SUM(
            CASE
                WHEN SUBSTR(
                    o.order_purchase_timestamp, 1, 7
                ) = ?
                THEN oi.price
                ELSE 0
            END
        ), 2) AS base_gmv,

        ROUND(SUM(
            CASE
                WHEN SUBSTR(
                    o.order_purchase_timestamp, 1, 7
                ) = ?
                THEN oi.price
                ELSE 0
            END
        ), 2) AS compare_gmv

    FROM orders AS o

    JOIN order_items AS oi
        ON o.order_id = oi.order_id

    JOIN products AS p
        ON oi.product_id = p.product_id

    WHERE o.order_status = 'delivered'
      AND SUBSTR(
          o.order_purchase_timestamp, 1, 7
      ) IN (?, ?)

    GROUP BY category;
    """

    result = pd.read_sql_query(
        query,
        conn,
        params=[
            base_month,
            compare_month,
            base_month,
            compare_month
        ]
    )

    result["gmv_change"] = (
        result["compare_gmv"]
        - result["base_gmv"]
    )

    result["change_pct"] = (
        result["gmv_change"]
        / result["base_gmv"]
        * 100
    )

    return result.sort_values("gmv_change")

In [133]:
category_result = get_category_contribution(
    "2018-07",
    "2018-08",
    conn
)

category_result.head(10).round(2)

                   category  base_gmv  compare_gmv  gmv_change  change_pct
68            watches_gifts  95164.79     69767.06   -25397.73      -26.69
40             garden_tools  25639.88     16314.70    -9325.18      -36.37
32          fixed_telephony   9319.39      2724.17    -6595.22      -70.77
54         office_furniture  13225.28      6758.87    -6466.41      -48.89
19               cool_stuff  21152.01     15794.89    -5357.12      -25.33
43        home_appliances_2  12597.32      7532.76    -5064.56      -40.20
21  costruction_tools_tools   5501.20      1255.77    -4245.43      -77.17
37          furniture_decor  45393.59     41168.55    -4225.04       -9.31
15           consoles_games   8519.11      4381.31    -4137.80      -48.57
47               housewares  62583.30     58763.36    -3819.94       -6.10

In [134]:
category_result.sort_values(
    "gmv_change",
    ascending=False
).head(10).round(2)

,category,base_gmv,compare_gmv,gmv_change,change_pct
41,health_beauty,103524.22,119391.01,15866.79,15.33
65,telephony,26492.68,36572.91,10080.23,38.05
16,construction_tools_construction,15237.47,22917.16,7679.69,50.40
7,bed_bath_table,54405.23,60891.09,6485.86,11.92
58,pet_shop,19343.85,24608.07,5264.22,27.21
34,food,3378.17,8174.18,4796.01,141.97
57,perfumery,20645.97,24839.74,4193.77,20.31
53,musical_instruments,7871.93,10519.34,2647.41,33.63
18,construction_tools_safety,1888.95,3970.22,2081.27,110.18
27,fashion_bags_accessories,6071.07,8127.53,2056.46,33.87

In [136]:
def compare_category(
    category_name,
    base_month,
    compare_month,
    conn
):
    query = """
    SELECT
        SUBSTR(o.order_purchase_timestamp, 1, 7) AS month,

        ROUND(SUM(oi.price), 2) AS gmv,

        COUNT(DISTINCT o.order_id) AS orders,

        COUNT(DISTINCT c.customer_unique_id) AS customers,

        COUNT(*) AS items,

        ROUND(AVG(oi.price), 2) AS avg_item_price

    FROM orders AS o

    JOIN customers AS c
        ON o.customer_id = c.customer_id

    JOIN order_items AS oi
        ON o.order_id = oi.order_id

    JOIN products AS p
        ON oi.product_id = p.product_id

    WHERE o.order_status = 'delivered'

      AND COALESCE(
            p.product_category_name_english,
            p.product_category_name,
            'unknown'
          ) = ?

      AND SUBSTR(
            o.order_purchase_timestamp, 1, 7
          ) IN (?, ?)

    GROUP BY month
    ORDER BY month;
    """

    result = pd.read_sql_query(
        query,
        conn,
        params=[
            category_name,
            base_month,
            compare_month
        ]
    )

    result["aov"] = (
        result["gmv"] / result["orders"]
    )

    result["avg_items_per_order"] = (
        result["items"] / result["orders"]
    )

    result = result.set_index("month")

    if (
        base_month not in result.index
        or compare_month not in result.index
    ):
        raise ValueError(
            "The category has no data in one of the selected months."
        )

    base = result.loc[base_month]
    compare = result.loc[compare_month]

    comparison = pd.DataFrame({
        "Base": base,
        "Compare": compare,
        "Change %": (
            (compare / base) - 1
        ) * 100
    })

    return comparison

In [137]:
compare_category(
    "watches_gifts",
    "2018-07",
    "2018-08",
    conn
).round(2)

                         Base   Compare  Change %
gmv                  95164.79  69767.06    -26.69
orders                 507.00    387.00    -23.67
customers              502.00    384.00    -23.51
items                  521.00    411.00    -21.11
avg_item_price         182.66    169.75     -7.07
aov                    187.70    180.28     -3.96
avg_items_per_order      1.03      1.06      3.35

In [138]:
compare_category(
    "health_beauty",
    "2018-07",
    "2018-08",
    conn
).round(2)

                          Base    Compare  Change %
gmv                  103524.22  119391.01     15.33
orders                  699.00     765.00      9.44
customers               694.00     765.00     10.23
items                   770.00     835.00      8.44
avg_item_price          134.45     142.98      6.34
aov                     148.10     156.07      5.38
avg_items_per_order       1.10       1.09     -0.91